### PR TITLE
Add tests for shellsyntax for /bin/tcsh

### PR DESCRIPTION
**Pull request by sturivny**

### CODE REVIEW

**Comment by dcantrell** [comment]
This one has merge conflicts for Dockerfile.test.

Also it looks like the tests failed due to tcsh syntax.

**Comment by sturivny** [comment]
Fixed merge conflict.
What do you mean by `tests failed due to tcsh syntax`?

**Comment by dcantrell** [comment]
The invalid_tcsh example script you provided is passing "tcsh -n".  I'm not sure why.  There may be an example script in the tcsh source code that is invalid.

**Comment by dcantrell** [comment]
Here's an example:

```
#!/bin/tcsh
if [ $name != $user ) then
    echo "Your name isn't your username"
else
    echo "Your name is your username"
endif
```

If I save that to test.tcsh and run `tcsh -n test.tcsh`, I get:

```
$ tcsh -n test.tcsh 
Too many )'s.
```

And the exit code is non-zero.  The same type check can be used for csh.

**Comment by sturivny** [comment]
So, I'll update PRs with a script that not passed `tcsh -n`.
Thanks for the explanation.

**Comment by sturivny** [comment]
Done

**Pull request merged**
