### PR TITLE
Make virus inspection failures WAIVABLE_BY_SECURITY.

### PR DESCRIPTION
**Pull request by msrb**
Fixes: #1025

Signed-off-by: Michal Srb <michal@redhat.com>

### CODE REVIEW

**Comment by msrb** [comment]
I will need to rebase this MR once the following PRs are merged:

- https://github.com/rpminspect/rpminspect/pull/1057
- https://github.com/rpminspect/rpminspect/pull/1056

**Comment by dcantrell** [comment]
Python check is failing.  Run "black test/test_virus.py" to fix things and then run "make flake8 && make black".  If those pass, it should pass in CI.

**Comment by msrb** [comment]
@dcantrell This is strange. "black" is complaining about completely unrelated files:
```
format: commands[0]> python -m black --check --diff .
--- /home/runner/work/rpminspect/rpminspect/test/test_kmod.py	2023-02-01 13:26:59.988149 +0000
+++ /home/runner/work/rpminspect/rpminspect/test/test_kmod.py	2023-02-01 13:27:10.082473 +0000
@@ -121,10 +121,11 @@
would reformat /home/runner/work/rpminspect/rpminspect/test/test_kmod.py
...
--- /home/runner/work/rpminspect/rpminspect/test/test_pathmigration.py	2023-02-01 13:26:59.988149 +0000
+++ /home/runner/work/rpminspect/rpminspect/test/test_pathmigration.py	2023-02-01 13:27:10.316456 +0000
@@ -69,10 +69,11 @@
```

What's even weirder is that when I run black on those 2 files directly, there are no issues reported:
```
$ python -m black --check --diff test/test_pathmigration.py  test/test_kmod.py
All done! ✨ 🍰 ✨
2 files would be left unchanged.
```

The problem seems to be only reproducible through tox:
```
$ tox -e format
format installed: black==23.1.0,click==8.1.3,mypy-extensions==0.4.3,packaging==23.0,pathspec==0.11.0,platformdirs==2.6.2,tomli==2.0.1,typing_extensions==4.4.0
format run-test-pre: PYTHONHASHSEED='1337139413'
format run-test: commands[0] | python -m black --check --diff .
--- /home/msrb/projects/osci/rpminspect/test/test_pathmigration.py	2023-02-01 08:34:42.889017 +0000
+++ /home/msrb/projects/osci/rpminspect/test/test_pathmigration.py	2023-02-01 15:53:12.491808 +0000
@@ -69,10 +69,11 @@

...
```

**Comment by dcantrell** [comment]
Weird.  I checked it locally too.  I should check the CI job that runs flake8 and black.

**Pull request merged**
